version: '3.8'

services:
  # consumer:
  #   image: node:20.14.0
  #   container_name: consumer
  #   volumes:
  #     - ./:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: sh -c "npm install && npm run build && npm run start:dev"
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
